name: Publish

on:
  workflow_dispatch:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: [completed]

env:
  DENO_DIR: ../deno_cache_dir

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2.0.0
        with:
          deno-version: v2.x

      - name: Cache Deno dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}

      - name: Publish package
        run: deno publish
